### ISSUE TITLE
2 times die => crash

### ISSUE THREAD

**Issue by ArcasCZ** [blay09/TrashSlot#13]
Hello there!

I found little bug in last version (read: all versions) of this usefull and user friendly mod. 

When you die and click respawn - all is OK. When you die second time and click respawn, you will get client crash (CR included below). 

Bug appears only on server (KCauldron with forge 1492).

http://pastebin.com/jRZbbrRW

**Comment by BlayTheNinth** [comment]
Does this happen on Vanilla Forge servers as well?

**Comment by ArcasCZ** [comment]
Nope. Only at KCauldron.

**Comment by BlayTheNinth** [comment]
Nothing I can do about it then.

**Comment by ArcasCZ** [comment]
Other inventory extensions, such as TConstruct armor or knapsack, are working. So, I think there is some way you can fix it.

**Comment by BlayTheNinth** [comment]
TConstruct stuff is done in a completely different way. They open a different GUI screen and with it, a different Container, meaning they have full control over it and don't have to patch the Vanilla one. The reason it crashes with KCauldron is because somewhere, KCauldron behaves differently than a Forge server would. While I could spend time trying to figure things out and create an ugly workaround, it's really not worth it.
