### ISSUE TITLE
Ability to lock the slot position

### ISSUE THREAD

**Issue by Disketaa** [blay09/TrashSlot#147]
I want to make static position for the trash slot, but I can't, right? I want to place it in one spot in my inventory, without any position editing later on

**Comment by Disketaa** [comment]
I found the file, but why is it not in the config folder?

**Comment by BlayTheNinth** [comment]
Because it is a frequently changing runtime-options file rather than a static configuration file for the mod. It updates whenever the player moves the slot, enables/disables it in a screen, or locks/unlocks it. It is also not meant to be shipped in modpacks, while files in the config folder generally would be.
