### ISSUE TITLE
1.11.2-7.4.3 Trashslot enchanting trash

### ISSUE THREAD

**Issue by SableDrake** [blay09/TrashSlot#30]
After leaving items in the trashslot for a while they suddenly becomes unbreaking 1.

![2017-03-30_10 08 57](https://cloud.githubusercontent.com/assets/7422727/24494188/b21b2952-1531-11e7-89b6-4d5c6f6c1d1e.png)

**Comment by BlayTheNinth** [comment]
Never heard of this before and wouldn't be able to come up with an explanation other than "some other mod did something weird". Does this happen consistently to you?

**Comment by Jomik** [comment]
This happens consistently for me, doesn't matter what item it is. If I trash an enchanted item, then any item I trash afterwards, will appear to have the enchantment, after some time (inventories closed and opened)

**Comment by BlayTheNinth** [comment]
Can both of you post your modlists so we can compare?

**Comment by Jomik** [comment]
Was a bit too long to just post here I feel, so here's a gist 👍 
https://gist.github.com/Jomik/701de4c3950803d139d047383adb28f1

I first noticed it with an enchanted item from Roguelike Dungeons, I'm not sure if it has ONLY happened with items from there, to be honest. We don't enchant too many items in our world, though I do recall trashing a vanilla enchanted armor piece and having the same issue.

**Comment by kreezxil** [comment]
I have reports that this in happening in my pack too. I think the easiest solution would be to vortex that last trash item to the void instead of allowing it to hang around as an extra item. If anything, you can have a button there that allows you to open up trash history and scroll through what you've thrown out for retrieval. But then wouldn't that essentially turn the trash slot into a bag of holding?

My modlist for the Colonial Expanson pack of which I am the developer is https://gist.github.com/52b6b0d8b1827e98d1e4b23d197e0021

**Comment by GrumpNugget** [comment]
It has happened to me in the past as well. it was actually a bit funny to have an unbreaking cobblestone etc i think it has something to do with throwing an enchanted item in there and the next item put on top will get the enchantment placed on it instead. usually after some amount of time left in the slot.

**Comment by BlayTheNinth** [comment]
This should be fixed in the latest 1.11.2/1.12 versions. Let me know if it's still happening.
